spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: HemsServer
  profiles:
    active: jdbc
  datasource:
    url: jdbc:h2:file:~/data/HemsServerDB;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1;AUTO_SERVER=true;
    driverClassName: org.h2.Driver
    username: hemsserver
    password: 1q2w3e4r
    initialization-mode: always
    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      path: /h2-console
      #web-url-path: localhost:10012/h2-console/
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  task:
    scheduling:
      pool:
        size: 10
        
hemsServer:
  application:
    certificateManager:
      keyPair:
        algorithm: RSA
        signatureAlgorithm: SHA256withRSA



      